name: Push Event Workflow

on: push 

jobs:
  unit-testing:
    runs-on: ubuntu-latest 
    
    steps:
    - name : Checkout code
      uses : actions/checkout@v2
      
    - name : Install Packages 
      run : |
        pip install pytest
        pip install torch torchvision torchaudio
      
    - name : Run tests 
      run : |
        pytest Assignment-1/ex1_test.py
        pytest Assignment-3/regression_test.py